### ISSUE TITLE
Чистота кода

### ISSUE THREAD

**Issue by alexmikhalevich** [semien/linux#3]
Эту константу конечно лучше обозвать. Делать вот такие магические константы - плохая практика. Это же касается и других констант в коде. https://github.com/semien/linux/blob/be35aaede99069a4340a49e05118aab0d07b301a/hw4/client.c#L19

**Comment by semyonish** [comment]
Не до конца понял, плохо, что это константы или то, что у них плохие названия?

**Comment by alexmikhalevich** [comment]
плохо, что магические числа в коде:)
лучше сделать что-то вроде
```
#define COMMAND_SIZE 1024
...
char command[COMMAND_SIZE];
```

**Comment by semyonish** [comment]
Поправил.
И как я сразу не догадался?)
